import { z } from "zod";

export const postSandboxFiatDepositSimulateSchema = z.object({
  PaymentMethodID: z.string(),
  FiatAmount: z.string().describe("The amount of the deposit."),
  FiatCurrency: z.enum([
    "AED",
    "ARS",
    "AUD",
    "BDT",
    "BHD",
    "BMD",
    "BRL",
    "CAD",
    "CHF",
    "CLP",
    "CNY",
    "COP",
    "CZK",
    "DKK",
    "ETB",
    "EUR",
    "GBP",
    "GHS",
    "HKD",
    "HUF",
    "IDR",
    "ILS",
    "INR",
    "JPY",
    "KRW",
    "KWD",
    "LKR",
    "MMK",
    "MWK",
    "MXN",
    "MYR",
    "NGN",
    "NOK",
    "NZD",
    "PHP",
    "PKR",
    "PLN",
    "RUB",
    "RWF",
    "SAR",
    "SEK",
    "SGD",
    "THB",
    "TRY",
    "TWD",
    "UAH",
    "UGX",
    "USD",
    "VEF",
    "VND",
    "XAF",
    "XOF",
    "ZAR",
  ]),
});

export type PostSandboxFiatDepositSimulateSchema = z.infer<typeof postSandboxFiatDepositSimulateSchema>;
